name: cdcl
channels:
  - defaults
  # - conda-forge
dependencies:
  - python==3.9
  - tensorflow
  - ipykernel
  - tqdm
  - matplotlib
  - scipy
  - opencv
  - scikit-learn
  - scikit-image