name: cdcl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - tensorflow<2.11
  - ipykernel
  - matplotlib
  - opencv
  - tqdm
  - scikit-image